#!/bin/sh
set -e
cd /p2pool-maza
env > /p2pool-maza/env
chown -R p2pool.maza /p2pool-maza/env
if [ ! -d /home/p2pool/data ] ; then 
   mkdir /home/p2pool/data 
fi
chown -R p2pool.maza /home/p2pool/data
if [ ! -d /home/p2pool/p2pool-web ] ; then 
   mkdir /home/p2pool/p2pool-web
fi
chown -R p2pool.maza /home/p2pool/p2pool-web
if [ ! -h /home/p2pool/.mazacoin ] ; then
   ln -sv /home/maza/.mazacoin /home/p2pool 
fi
if [ -f /p2pool-maza/.firstrun ] 
   # wait for mazacoind to set a new rpcpassword and then start
   then sleep 120
   rm /p2pool-maza/.firstrun
fi
test -f /home/maza/.mazacoin/mazacoin.conf || cp /home/p2pool/rpcpass.conf /home/maza/.mazacoin.conf
exec su p2pool -c ./start_p2pool_maza.sh
